CREATE MATERIALIZED VIEW instancedata_last_point_aws 
ENGINE = AggregatingMergeTree() PARTITION BY tuple() 
ORDER BY (provider, operatingSystem, region, instanceType) POPULATE AS 
SELECT 
    provider,
    maxState(crawlTime) AS max_crawlTime,
    region,
    operatingSystem,
    argMaxState(priceType, crawlTime) AS priceType,
    argMaxState(pricePerHour, crawlTime) AS pricePerHour,
    argMaxState(priceUpfront, crawlTime) AS priceUpfront,
    argMaxState(vcpu, crawlTime) AS vcpu, 
    argMaxState(memory, crawlTime) AS memory,
    argMaxState(gpu, crawlTime) AS gpu,
    argMaxState(capacityStatus, crawlTime) AS capacityStatus,
    argMaxState(clockSpeedIsUpTo, crawlTime) AS clockSpeedIsUpTo,
    argMaxState(clockSpeed, crawlTime) AS clockSpeed,
    argMaxState(currentGeneration, crawlTime) AS currentGeneration,
    argMaxState(dedicatedEbsThroughputIsUpTo, crawlTime) AS dedicatedEbsThroughputIsUpTo,
    argMaxState(dedicatedEbsThroughput, crawlTime) AS dedicatedEbsThroughput,
    argMaxState(ebsOptimized, crawlTime) AS ebsOptimized,
    argMaxState(ecuIsVariable, crawlTime) AS ecuIsVariable,
    argMaxState(ecu, crawlTime) AS ecu,
    argMaxState(elasticGraphicsType, crawlTime) AS elasticGraphicsType,
    argMaxState(enhancedNetworkingSupported, crawlTime) AS enhancedNetworkingSupported,
    argMaxState(fromLocation, crawlTime) AS fromLocation,
    argMaxState(fromLocationType, crawlTime) AS fromLocationType,
    argMaxState(gpuMemory, crawlTime) AS gpuMemory,
    argMaxState(group, crawlTime) AS group,
    argMaxState(groupDescription, crawlTime) AS groupDescription,
    argMaxState(instance, crawlTime) AS instance,
    argMaxState(instanceCapacity10xlarge, crawlTime) AS instanceCapacity10xlarge,
    argMaxState(instanceCapacity12xlarge, crawlTime) AS instanceCapacity12xlarge,
    argMaxState(instanceCapacity16xlarge, crawlTime) AS instanceCapacity16xlarge,
    argMaxState(instanceCapacity18xlarge, crawlTime) AS instanceCapacity18xlarge,
    argMaxState(instanceCapacity24xlarge, crawlTime) AS instanceCapacity24xlarge,
    argMaxState(instanceCapacity2xlarge, crawlTime) AS instanceCapacity2xlarge,
    argMaxState(instanceCapacity32xlarge, crawlTime) AS instanceCapacity32xlarge,
    argMaxState(instanceCapacity4xlarge, crawlTime) AS instanceCapacity4xlarge,
    argMaxState(instanceCapacity8xlarge, crawlTime) AS instanceCapacity8xlarge,
    argMaxState(instanceCapacity9xlarge, crawlTime) AS instanceCapacity9xlarge,
    argMaxState(instanceCapacityLarge, crawlTime) AS instanceCapacityLarge,
    argMaxState(instanceCapacityMedium, crawlTime) AS instanceCapacityMedium,
    argMaxState(instanceCapacityXlarge, crawlTime) AS instanceCapacityXlarge,
    argMaxState(instanceFamily, crawlTime) AS instanceFamily,
    instanceType,
    argMaxState(intelAvx2Available, crawlTime) AS intelAvx2Available,
    argMaxState(intelAvxAvailable, crawlTime) AS intelAvxAvailable,
    argMaxState(intelTurboAvailable, crawlTime) AS intelTurboAvailable,
    argMaxState(licenseModel, crawlTime) AS licenseModel,
    argMaxState(location, crawlTime) AS location,
    argMaxState(locationType, crawlTime) AS locationType,
    argMaxState(maxIopsBurstPerformance, crawlTime) AS maxIopsBurstPerformance,
    argMaxState(maxIopsVolume, crawlTime) AS maxIopsVolume,
    argMaxState(maxThroughputVolume, crawlTime) AS maxThroughputVolume,
    argMaxState(maxVolumeSize, crawlTime) AS maxVolumeSize,
    argMaxState(networkPerformance, crawlTime) AS networkPerformance,
    argMaxState(normalizationSizeFactor, crawlTime) AS normalizationSizeFactor,
    argMaxState(operation, crawlTime) AS operation,
    argMaxState(physicalCores, crawlTime) AS physicalCores,
    argMaxState(physicalProcessor, crawlTime) AS physicalProcessor,
    argMaxState(preInstalledSw, crawlTime) AS preInstalledSw,
    argMaxState(processorArchitecture, crawlTime) AS processorArchitecture,
    argMaxState(processorFeatures, crawlTime) AS processorFeatures,
    argMaxState(productFamily, crawlTime) AS productFamily,
    argMaxState(provisioned, crawlTime) AS provisioned,
    argMaxState(serviceName, crawlTime) AS serviceName,
    argMaxState(sku, crawlTime) AS sku,
    argMaxState(storageIsEbsOnly, crawlTime) AS storageIsEbsOnly,
    argMaxState(storageCount, crawlTime) AS storageCount,
    argMaxState(storageCapacity, crawlTime) AS storageCapacity,
    argMaxState(storageType, crawlTime) AS storageType,
    argMaxState(storageMedia, crawlTime) AS storageMedia,
    argMaxState(tenancy, crawlTime) AS tenancy,
    argMaxState(toLocation, crawlTime) AS toLocation,
    argMaxState(toLocationType, crawlTime) AS toLocationType,
    argMaxState(transferType, crawlTime) AS transferType,
    argMaxState(usageType, crawlTime) AS usageType,
    argMaxState(volumeType, crawlTime) AS volumeType,
    argMaxState(appliesTo, crawlTime) AS appliesTo,
    argMaxState(description, crawlTime) AS description,
    argMaxState(effectiveDate, crawlTime) AS effectiveDate,
    argMaxState(beginRange, crawlTime) AS beginRange,
    argMaxState(endRange, crawlTime) AS endRange,
    argMaxState(leaseContractLength, crawlTime) AS leaseContractLength,
    argMaxState(offeringClass, crawlTime) AS offeringClass,
    argMaxState(purchaseOption, crawlTime) AS purchaseOption
FROM instancedata
GROUP BY 
    provider,
    instanceType,
    region, 
    operatingSystem
