CREATE VIEW instancedata_last_point_aws_v AS
SELECT 
    provider,
    maxMerge(max_crawlTime) AS crawlTime,
    region,
    operatingSystem,
    argMaxMerge(priceType) AS priceType,
    argMaxMerge(pricePerHour) AS pricePerHour,
    argMaxMerge(priceUpfront) AS priceUpfront,
    argMaxMerge(vcpu) AS vcpu, 
    argMaxMerge(memory) AS memory,
    argMaxMerge(gpu) AS gpu,
    argMaxMerge(capacityStatus) AS capacityStatus,
    argMaxMerge(clockSpeedIsUpTo) AS clockSpeedIsUpTo,
    argMaxMerge(clockSpeed) AS clockSpeed,
    argMaxMerge(currentGeneration) AS currentGeneration,
    argMaxMerge(dedicatedEbsThroughputIsUpTo) AS dedicatedEbsThroughputIsUpTo,
    argMaxMerge(dedicatedEbsThroughput) AS dedicatedEbsThroughput,
    argMaxMerge(ebsOptimized) AS ebsOptimized,
    argMaxMerge(ecuIsVariable) AS ecuIsVariable,
    argMaxMerge(ecu) AS ecu,
    argMaxMerge(elasticGraphicsType) AS elasticGraphicsType,
    argMaxMerge(enhancedNetworkingSupported) AS enhancedNetworkingSupported,
    argMaxMerge(fromLocation) AS fromLocation,
    argMaxMerge(fromLocationType) AS fromLocationType,
    argMaxMerge(gpuMemory) AS gpuMemory,
    argMaxMerge(group) AS group,
    argMaxMerge(groupDescription) AS groupDescription,
    argMaxMerge(instance) AS instance,
    argMaxMerge(instanceCapacity10xlarge) AS instanceCapacity10xlarge,
    argMaxMerge(instanceCapacity12xlarge) AS instanceCapacity12xlarge,
    argMaxMerge(instanceCapacity16xlarge) AS instanceCapacity16xlarge,
    argMaxMerge(instanceCapacity18xlarge) AS instanceCapacity18xlarge,
    argMaxMerge(instanceCapacity24xlarge) AS instanceCapacity24xlarge,
    argMaxMerge(instanceCapacity2xlarge) AS instanceCapacity2xlarge,
    argMaxMerge(instanceCapacity32xlarge) AS instanceCapacity32xlarge,
    argMaxMerge(instanceCapacity4xlarge) AS instanceCapacity4xlarge,
    argMaxMerge(instanceCapacity8xlarge) AS instanceCapacity8xlarge,
    argMaxMerge(instanceCapacity9xlarge) AS instanceCapacity9xlarge,
    argMaxMerge(instanceCapacityLarge) AS instanceCapacityLarge,
    argMaxMerge(instanceCapacityMedium) AS instanceCapacityMedium,
    argMaxMerge(instanceCapacityXlarge) AS instanceCapacityXlarge,
    argMaxMerge(instanceFamily) AS instanceFamily,
    instanceType,
    argMaxMerge(intelAvx2Available) AS intelAvx2Available,
    argMaxMerge(intelAvxAvailable) AS intelAvxAvailable,
    argMaxMerge(intelTurboAvailable) AS intelTurboAvailable,
    argMaxMerge(licenseModel) AS licenseModel,
    argMaxMerge(location) AS location,
    argMaxMerge(locationType) AS locationType,
    argMaxMerge(maxIopsBurstPerformance) AS maxIopsBurstPerformance,
    argMaxMerge(maxIopsVolume) AS maxIopsVolume,
    argMaxMerge(maxThroughputVolume) AS maxThroughputVolume,
    argMaxMerge(maxVolumeSize) AS maxVolumeSize,
    argMaxMerge(networkPerformance) AS networkPerformance,
    argMaxMerge(normalizationSizeFactor) AS normalizationSizeFactor,
    argMaxMerge(operation) AS operation,
    argMaxMerge(physicalCores) AS physicalCores,
    argMaxMerge(physicalProcessor) AS physicalProcessor,
    argMaxMerge(preInstalledSw) AS preInstalledSw,
    argMaxMerge(processorArchitecture) AS processorArchitecture,
    argMaxMerge(processorFeatures) AS processorFeatures,
    argMaxMerge(productFamily) AS productFamily,
    argMaxMerge(provisioned) AS provisioned,
    argMaxMerge(serviceName) AS serviceName,
    argMaxMerge(sku) AS sku,
    argMaxMerge(storageIsEbsOnly) AS storageIsEbsOnly,
    argMaxMerge(storageCount) AS storageCount,
    argMaxMerge(storageCapacity) AS storageCapacity,
    argMaxMerge(storageType) AS storageType,
    argMaxMerge(storageMedia) AS storageMedia,
    argMaxMerge(tenancy) AS tenancy,
    argMaxMerge(toLocation) AS toLocation,
    argMaxMerge(toLocationType) AS toLocationType,
    argMaxMerge(transferType) AS transferType,
    argMaxMerge(usageType) AS usageType,
    argMaxMerge(volumeType) AS volumeType,
    argMaxMerge(appliesTo) AS appliesTo,
    argMaxMerge(description) AS description,
    argMaxMerge(effectiveDate) AS effectiveDate,
    argMaxMerge(beginRange) AS beginRange,
    argMaxMerge(endRange) AS endRange,
    argMaxMerge(leaseContractLength) AS leaseContractLength,
    argMaxMerge(offeringClass) AS offeringClass,
    argMaxMerge(purchaseOption) AS purchaseOption
FROM instancedata_last_point_aws
GROUP BY 
    provider,
    instanceType,
    region, 
    operatingSystem
